
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Button button10;

	private global::Gtk.Button button11;

	private global::Gtk.Button button12;

	private global::Gtk.Button button13;

	private global::Gtk.Button button14;

	private global::Gtk.Button button15;

	private global::Gtk.Button button16;

	private global::Gtk.Button button17;

	private global::Gtk.Button button18;

	private global::Gtk.Button button19;

	private global::Gtk.Button button20;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView answerReturned;

	private global::Gtk.Label label4;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView file;

	private global::Gtk.ScrolledWindow GtkScrolledWindow7;

	private global::Gtk.TextView server;

	private global::Gtk.Label label5;

	private global::Gtk.ScrolledWindow GtkScrolledWindow6;

	private global::Gtk.TextView database;

	private global::Gtk.ScrolledWindow GtkScrolledWindow5;

	private global::Gtk.TextView password;

	private global::Gtk.ScrolledWindow GtkScrolledWindow4;

	private global::Gtk.TextView username;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView port;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView task;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 800;
		this.HeightRequest = 450;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.WidthRequest = 300;
		this.fixed1.HeightRequest = 300;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Task 1 F#");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w1.X = 10;
		w1.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Task 2 F#");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w2.X = 10;
		w2.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Task 3 F#");
		this.fixed1.Add(this.button3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
		w3.X = 10;
		w3.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Task 4 F#");
		this.fixed1.Add(this.button4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
		w4.X = 10;
		w4.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Task 5 F#");
		this.fixed1.Add(this.button5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
		w5.X = 10;
		w5.Y = 170;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Task 6 F#");
		this.fixed1.Add(this.button6);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button6]));
		w6.X = 10;
		w6.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Task 7 F#");
		this.fixed1.Add(this.button7);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button7]));
		w7.X = 10;
		w7.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("Task 8 F #");
		this.fixed1.Add(this.button8);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button8]));
		w8.X = 10;
		w8.Y = 290;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("Task 9 F#");
		this.fixed1.Add(this.button9);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button9]));
		w9.X = 10;
		w9.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button10 = new global::Gtk.Button();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString("Task 10 F#");
		this.fixed1.Add(this.button10);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button10]));
		w10.X = 10;
		w10.Y = 370;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("Task 11 SQL");
		this.fixed1.Add(this.button11);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button11]));
		w11.X = 780;
		w11.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button12 = new global::Gtk.Button();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString("Task 12 SQL");
		this.fixed1.Add(this.button12);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button12]));
		w12.X = 780;
		w12.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("Task 13 SQL");
		this.fixed1.Add(this.button13);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button13]));
		w13.X = 780;
		w13.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button14 = new global::Gtk.Button();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString("Task 14 SQL");
		this.fixed1.Add(this.button14);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button14]));
		w14.X = 780;
		w14.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("Task 15 SQL");
		this.fixed1.Add(this.button15);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button15]));
		w15.X = 780;
		w15.Y = 170;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button16 = new global::Gtk.Button();
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = global::Mono.Unix.Catalog.GetString("Task 16 SQL");
		this.fixed1.Add(this.button16);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button16]));
		w16.X = 780;
		w16.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button17 = new global::Gtk.Button();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString("Task 17 SQL");
		this.fixed1.Add(this.button17);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button17]));
		w17.X = 780;
		w17.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button18 = new global::Gtk.Button();
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString("Task 18 SQL");
		this.fixed1.Add(this.button18);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button18]));
		w18.X = 780;
		w18.Y = 290;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button19 = new global::Gtk.Button();
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString("Task 19 SQL");
		this.fixed1.Add(this.button19);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button19]));
		w19.X = 780;
		w19.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button20 = new global::Gtk.Button();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString("Task 20 SQL");
		this.fixed1.Add(this.button20);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button20]));
		w20.X = 780;
		w20.Y = 370;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("FileName for F# (include .csv)");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w21.X = 10;
		w21.Y = 420;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("input (needed for Taks 1-3 in F#, Task 1 for SQL)");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w22.X = 191;
		w22.Y = 420;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.answerReturned = new global::Gtk.TextView();
		this.answerReturned.Buffer.Text = global::Mono.Unix.Catalog.GetString("output go");
		this.answerReturned.WidthRequest = 490;
		this.answerReturned.HeightRequest = 350;
		this.answerReturned.CanFocus = true;
		this.answerReturned.Name = "answerReturned";
		this.GtkScrolledWindow.Add(this.answerReturned);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w24.X = 178;
		w24.Y = 32;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("port");
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w25.X = 166;
		w25.Y = 530;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("password");
		this.fixed1.Add(this.label6);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
		w26.X = 505;
		w26.Y = 530;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("database");
		this.fixed1.Add(this.label7);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
		w27.X = 682;
		w27.Y = 528;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("server");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w28.X = 48;
		w28.Y = 530;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.file = new global::Gtk.TextView();
		this.file.WidthRequest = 10;
		this.file.HeightRequest = 10;
		this.file.CanFocus = true;
		this.file.Name = "file";
		this.GtkScrolledWindow1.Add(this.file);
		this.fixed1.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow1]));
		w30.X = 43;
		w30.Y = 450;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow7 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow7.Name = "GtkScrolledWindow7";
		this.GtkScrolledWindow7.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow7.Gtk.Container+ContainerChild
		this.server = new global::Gtk.TextView();
		this.server.WidthRequest = 3;
		this.server.HeightRequest = 3;
		this.server.CanFocus = true;
		this.server.Name = "server";
		this.GtkScrolledWindow7.Add(this.server);
		this.fixed1.Add(this.GtkScrolledWindow7);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow7]));
		w32.X = 41;
		w32.Y = 558;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("usename");
		this.fixed1.Add(this.label5);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
		w33.X = 326;
		w33.Y = 530;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
		this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
		this.database = new global::Gtk.TextView();
		this.database.CanFocus = true;
		this.database.Name = "database";
		this.GtkScrolledWindow6.Add(this.database);
		this.fixed1.Add(this.GtkScrolledWindow6);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow6]));
		w35.X = 681;
		w35.Y = 554;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
		this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
		this.password = new global::Gtk.TextView();
		this.password.CanFocus = true;
		this.password.Name = "password";
		this.GtkScrolledWindow5.Add(this.password);
		this.fixed1.Add(this.GtkScrolledWindow5);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow5]));
		w37.X = 510;
		w37.Y = 553;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.username = new global::Gtk.TextView();
		this.username.CanFocus = true;
		this.username.Name = "username";
		this.GtkScrolledWindow4.Add(this.username);
		this.fixed1.Add(this.GtkScrolledWindow4);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow4]));
		w39.X = 325;
		w39.Y = 556;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.port = new global::Gtk.TextView();
		this.port.CanFocus = true;
		this.port.Name = "port";
		this.GtkScrolledWindow3.Add(this.port);
		this.fixed1.Add(this.GtkScrolledWindow3);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow3]));
		w41.X = 167;
		w41.Y = 556;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.task = new global::Gtk.TextView();
		this.task.CanFocus = true;
		this.task.Name = "task";
		this.GtkScrolledWindow2.Add(this.task);
		this.fixed1.Add(this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow2]));
		w43.X = 278;
		w43.Y = 445;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 918;
		this.DefaultHeight = 666;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.button6.Clicked += new global::System.EventHandler(this.OnButton6Clicked);
		this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		this.button8.Clicked += new global::System.EventHandler(this.OnButton8Clicked);
		this.button9.Clicked += new global::System.EventHandler(this.OnButton9Clicked);
		this.button10.Clicked += new global::System.EventHandler(this.OnButton10Clicked);
		this.button11.Clicked += new global::System.EventHandler(this.OnButton11Clicked);
		this.button12.Clicked += new global::System.EventHandler(this.OnButton12Clicked);
		this.button13.Clicked += new global::System.EventHandler(this.OnButton13Clicked);
		this.button14.Clicked += new global::System.EventHandler(this.OnButton14Clicked);
		this.button15.Clicked += new global::System.EventHandler(this.OnButton15Clicked);
		this.button16.Clicked += new global::System.EventHandler(this.OnButton16Clicked);
		this.button17.Clicked += new global::System.EventHandler(this.OnButton17Clicked);
		this.button18.Clicked += new global::System.EventHandler(this.OnButton18Clicked);
		this.button19.Clicked += new global::System.EventHandler(this.OnButton19Clicked);
		this.button20.Clicked += new global::System.EventHandler(this.OnButton20Clicked);
	}
}
